name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      working-directory: ${{runner.workspace}}
      run: |
        cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=release

    - name: Build Release
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: cmake --build . --config release -j 4

    - name: Test Release
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: ctest -L UnoTest

    - name: Create package
      id: package
      run: |
        PACKAGE_NAME=sailgame.uno-provider.${GITHUB_REF#refs/tags/}.${{ matrix.os }}.tar.gz
        cp README.md build/
        cp LICENSE build/
        tar -czvf $PACKAGE_NAME -C build .
        echo ::set-output name=name::${PACKAGE_NAME}

    - name: Upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ steps.package.outputs.name }}
        asset_name: ${{ steps.package.outputs.name }}
        asset_content_type: application/gzip