name: CI

on:
  push:
    branches:
      - main
      - ci-trial
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * * # daily at 00:00

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        build_type: [debug, release]
    env:
      MY_INSTALL_DIR: ~/.local
      GRPC_VERSION: 1.32.0

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Cache grpc
      uses: actions/cache@v2
      id: grpc-cache
      with:
        path: ${{env.MY_INSTALL_DIR}}
        key: ${{ runner.os }}-grpc-${{ env.GRPC_VERSION }}

    - name: Set up dependencies
      if: steps.grpc-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt install -y protobuf-compiler libprotobuf-dev
        mkdir -p $MY_INSTALL_DIR
        git clone --recurse-submodules -b v${{ env.GRPC_VERSION }} https://github.com/grpc/grpc
        cd grpc
        mkdir -p cmake/build
        pushd cmake/build
        cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR -DBENCHMARK_ENABLE_TESTING=OFF ../..
        make -j 8
        make install

    - name: Create Build Environment
      working-directory: ${{runner.workspace}}
      run: |
        cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build/
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_PREFIX_PATH=$MY_INSTALL_DIR

    - name: Cache externals
      uses: actions/cache@v2
      with:
        path: ${{ runner.workspace }}/build/lib
        key: ${{ runner.os }}-build-${{ matrix.build_type }}-${{ hashFiles('lib/**/CMakeLists.txt') }}

    - name: Build
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: 
        cmake --build . --config ${{ matrix.build_type }} -j 4

    - name: Test
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: ctest -L UnoTest

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        build_type: [debug, release]
    env:
      MY_INSTALL_DIR: ~/.local
      GRPC_VERSION: 1.32.0

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
      
    - name: Cache grpc
      uses: actions/cache@v2
      id: grpc-cache
      with:
        path: ${{env.MY_INSTALL_DIR}}
        key: ${{ runner.os }}-grpc-${{ env.GRPC_VERSION }}

    - name: Set up dependencies
      if: steps.grpc-cache.outputs.cache-hit != 'true'
      run: |
        brew install protobuf
        mkdir -p $MY_INSTALL_DIR
        git clone --recurse-submodules -b v${{ env.GRPC_VERSION }} https://github.com/grpc/grpc
        cd grpc
        mkdir -p cmake/build
        pushd cmake/build
        cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR -DBENCHMARK_ENABLE_TESTING=OFF ../..
        make -j 8
        make install

    - name: Create Build Environment
      working-directory: ${{runner.workspace}}
      run: |
        cmake -E make_directory build
        which cmake

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build/
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_PREFIX_PATH=$MY_INSTALL_DIR
        which cmake

    - name: Cache externals
      uses: actions/cache@v2
      with:
        path: ${{ runner.workspace }}/build/lib
        key: ${{ runner.os }}-build-${{ matrix.build_type }}-${{ hashFiles('lib/**/CMakeLists.txt') }}

    - name: Build
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: |
        export CMAKE_ROOT=/usr/local/bin
        which cmake
        cmake --build . 
        which cmake
        
    - name: Test
      working-directory: ${{runner.workspace}}/build/
      shell: bash
      run: ctest -L UnoTest
